/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Credential login against seeded users (ADR-0006). Replaces the Phase 0
         *     dev-token stub. Claims (sub, org_id, role) drive the RLS tenant context.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["hello_api_v1_hello_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/royalty/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invoices
         * @description Invoices visible to the caller (RLS-scoped), optionally for one run.
         */
        get: operations["list_invoices_api_v1_royalty_invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/royalty/invoices/aging": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Invoice Aging
         * @description Unpaid live invoices bucketed 0-30 / 31-60 / 61-90 / 90+ days (HQ).
         */
        get: operations["invoice_aging_api_v1_royalty_invoices_aging_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/royalty/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description Reports visible to the caller (RLS-scoped), optionally filtered.
         */
        get: operations["list_reports_api_v1_royalty_reports_get"];
        put?: never;
        /**
         * Create Report
         * @description Create a draft revenue report for one location and period (operator).
         */
        post: operations["create_report_api_v1_royalty_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/royalty/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Report
         * @description Edit a draft's figures; a locked report raises report_locked (409).
         */
        patch: operations["update_report_api_v1_royalty_reports__report_id__patch"];
        trace?: never;
    };
    "/api/v1/royalty/reports/{report_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Correction
         * @description Correct a locked report: new draft linked to it via supersedes.
         */
        post: operations["create_correction_api_v1_royalty_reports__report_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/royalty/reports/{report_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Report
         * @description Attest and submit: draft→submitted→locked atomically (R3).
         */
        post: operations["submit_report_api_v1_royalty_reports__report_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/royalty/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description All run versions, optionally for one period (HQ).
         */
        get: operations["list_runs_api_v1_royalty_runs_get"];
        put?: never;
        /**
         * Run Royalty Period
         * @description Run the period over current locked reports (HQ). Idempotent + versioned (R4).
         */
        post: operations["run_royalty_period_api_v1_royalty_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/royalty/runs/{run_id}/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue Invoices
         * @description Issue one net-30 invoice per (run, org) (HQ). Reissuing supersedes, never edits.
         */
        post: operations["issue_invoices_api_v1_royalty_runs__run_id__invoices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/royalty/runs/{run_id}/line-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Line Items
         * @description A run's line items; operators see only their own rows (RLS).
         */
        get: operations["list_line_items_api_v1_royalty_runs__run_id__line_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgingBucketOut */
        AgingBucketOut: {
            /** Amount Due Cents */
            amount_due_cents: number;
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "0-30" | "31-60" | "61-90" | "90+";
            /** Invoice Count */
            invoice_count: number;
        };
        /** AgingInvoiceOut */
        AgingInvoiceOut: {
            /** Amount Due Cents */
            amount_due_cents: number;
            /**
             * Bucket
             * @enum {string}
             */
            bucket: "0-30" | "31-60" | "61-90" | "90+";
            /** Days Outstanding */
            days_outstanding: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** AgingOut */
        AgingOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Buckets */
            buckets: components["schemas"]["AgingBucketOut"][];
            /** Invoices */
            invoices: components["schemas"]["AgingInvoiceOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HelloResponse */
        HelloResponse: {
            /**
             * Db Time
             * Format: date-time
             */
            db_time: string;
            /** Environment */
            environment: string;
            /** Message */
            message: string;
        };
        /** InvoiceOut */
        InvoiceOut: {
            /** Amount Due Cents */
            amount_due_cents: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "issued" | "paid" | "overdue";
            /** Superseded By */
            superseded_by: string | null;
        };
        /** IssueInvoicesOut */
        IssueInvoicesOut: {
            /** Invoices */
            invoices: components["schemas"]["InvoiceOut"][];
            /**
             * Reused
             * @description True when invoices for this run already existed and were returned as-is
             */
            reused: boolean;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** RevenueReportCreate */
        RevenueReportCreate: {
            /** Gross Cents */
            gross_cents: number;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /**
             * Period
             * Format: date
             */
            period: string;
            /** Refunds Cents */
            refunds_cents: number;
        };
        /** RevenueReportOut */
        RevenueReportOut: {
            /** Attested At */
            attested_at: string | null;
            /** Attested By */
            attested_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Gross Cents */
            gross_cents: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Net Base Cents */
            net_base_cents: number;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Period
             * Format: date
             */
            period: string;
            /** Refunds Cents */
            refunds_cents: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "submitted" | "locked";
            /** Supersedes */
            supersedes: string | null;
        };
        /** RevenueReportUpdate */
        RevenueReportUpdate: {
            /** Gross Cents */
            gross_cents: number;
            /** Refunds Cents */
            refunds_cents: number;
        };
        /** RoyaltyLineItemOut */
        RoyaltyLineItemOut: {
            /** Adjustments Cents */
            adjustments_cents: number;
            /** Amount Due Cents */
            amount_due_cents: number;
            /** Base Cents */
            base_cents: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Minimum Applied */
            minimum_applied: boolean;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Rate */
            rate: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** RoyaltyRunOut */
        RoyaltyRunOut: {
            /** Exclusions */
            exclusions: components["schemas"]["RunExclusionOut"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Fingerprint */
            input_fingerprint: string;
            /** Line Items */
            line_items: components["schemas"]["RoyaltyLineItemOut"][];
            /**
             * Period
             * Format: date
             */
            period: string;
            /**
             * Reused
             * @description True when idempotency returned an existing version instead of creating one
             */
            reused: boolean;
            /** Version */
            version: number;
        };
        /** RoyaltyRunRequest */
        RoyaltyRunRequest: {
            /**
             * Period
             * Format: date
             */
            period: string;
        };
        /** RoyaltyRunSummaryOut */
        RoyaltyRunSummaryOut: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Input Fingerprint */
            input_fingerprint: string;
            /**
             * Period
             * Format: date
             */
            period: string;
            /** Version */
            version: number;
        };
        /** RunExclusionOut */
        RunExclusionOut: {
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Reason */
            reason: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    hello_api_v1_hello_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelloResponse"];
                };
            };
        };
    };
    list_invoices_api_v1_royalty_invoices_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invoice_aging_api_v1_royalty_invoices_aging_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_v1_royalty_reports_get: {
        parameters: {
            query?: {
                period?: string | null;
                location_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevenueReportOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_v1_royalty_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevenueReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevenueReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_report_api_v1_royalty_reports__report_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevenueReportUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevenueReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_correction_api_v1_royalty_reports__report_id__corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevenueReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_report_api_v1_royalty_reports__report_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevenueReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_royalty_runs_get: {
        parameters: {
            query?: {
                period?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoyaltyRunSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_royalty_period_api_v1_royalty_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoyaltyRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoyaltyRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_invoices_api_v1_royalty_runs__run_id__invoices_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueInvoicesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_line_items_api_v1_royalty_runs__run_id__line_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoyaltyLineItemOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
