"""phase 7 portal tables

Revision ID: 21eae3d52b30
Revises: 96e322848d4f
Create Date: 2026-08-05 06:19:36.317553

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "21eae3d52b30"
down_revision: str | None = "96e322848d4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "onboarding_tasks",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("due_offset_days", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("due_offset_days >= 0", name="ck_onboarding_due_offset_non_negative"),
        sa.ForeignKeyConstraint(
            ["completed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "sort_order", name="uq_onboarding_tasks_org_sort"),
    )
    op.create_index(
        op.f("ix_onboarding_tasks_org_id"), "onboarding_tasks", ["org_id"], unique=False
    )
    op.create_table(
        "portal_documents",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portal_documents_org_id"), "portal_documents", ["org_id"], unique=False
    )
    op.create_table(
        "product_orders",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "submitted", "fulfilled", name="order_status"),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_orders_location_id"), "product_orders", ["location_id"], unique=False
    )
    op.create_index(op.f("ix_product_orders_org_id"), "product_orders", ["org_id"], unique=False)
    op.create_table(
        "product_order_lines",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("qty > 0", name="ck_order_lines_qty_positive"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["product_orders.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", "product_id", name="uq_order_lines_order_product"),
    )
    op.create_index(
        op.f("ix_product_order_lines_order_id"), "product_order_lines", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_order_lines_org_id"), "product_order_lines", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_order_lines_product_id"),
        "product_order_lines",
        ["product_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Standard tenant isolation (ADR-0002) on every portal table.
    for t in ("onboarding_tasks", "portal_documents", "product_orders", "product_order_lines"):
        op.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {t} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {t}
                USING (current_setting('app.role', true) = 'hq_admin'
                       OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
                WITH CHECK (current_setting('app.role', true) = 'hq_admin'
                            OR org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)
            """
        )
        op.execute(
            f"""
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'cnos_app') THEN
                    GRANT SELECT, INSERT, UPDATE, DELETE ON {t} TO cnos_app;
                END IF;
            END
            $$
            """
        )


def downgrade() -> None:
    for t in ("product_order_lines", "product_orders", "portal_documents", "onboarding_tasks"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {t}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_order_lines_product_id"), table_name="product_order_lines")
    op.drop_index(op.f("ix_product_order_lines_org_id"), table_name="product_order_lines")
    op.drop_index(op.f("ix_product_order_lines_order_id"), table_name="product_order_lines")
    op.drop_table("product_order_lines")
    op.drop_index(op.f("ix_product_orders_org_id"), table_name="product_orders")
    op.drop_index(op.f("ix_product_orders_location_id"), table_name="product_orders")
    op.drop_table("product_orders")
    op.drop_index(op.f("ix_portal_documents_org_id"), table_name="portal_documents")
    op.drop_table("portal_documents")
    op.drop_index(op.f("ix_onboarding_tasks_org_id"), table_name="onboarding_tasks")
    op.drop_table("onboarding_tasks")
    # ### end Alembic commands ###
