"""phase 1 schema

Revision ID: fff849ab3deb
Revises:
Create Date: 2026-08-05 03:49:34.177354

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fff849ab3deb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orgs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("hq", "operator", name="org_kind"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("sku", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column("price_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_table(
        "royalty_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("input_fingerprint", sa.Text(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("period", "version", name="uq_royalty_runs_period_version"),
    )
    op.create_index(op.f("ix_royalty_runs_period"), "royalty_runs", ["period"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("amount_due_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "status", sa.Enum("issued", "paid", "overdue", name="invoice_status"), nullable=False
        ),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["royalty_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "org_id", name="uq_invoices_run_org"),
    )
    op.create_index(op.f("ix_invoices_org_id"), "invoices", ["org_id"], unique=False)
    op.create_index(op.f("ix_invoices_run_id"), "invoices", ["run_id"], unique=False)
    op.create_table(
        "license_agreements",
        sa.Column("royalty_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("base_definition", sa.Text(), nullable=False),
        sa.Column("monthly_minimum_cents", sa.BigInteger(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_license_agreements_org_id"), "license_agreements", ["org_id"], unique=False
    )
    op.create_table(
        "locations",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("activated_on", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_locations_org_id"), "locations", ["org_id"], unique=False)
    op.create_table(
        "lots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("lot_code", sa.Text(), nullable=False),
        sa.Column("supplier", sa.Text(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lot_code"),
    )
    op.create_index(op.f("ix_lots_product_id"), "lots", ["product_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("hq_admin", "operator", "clinic_staff", name="user_role"),
            nullable=False,
        ),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_table(
        "leads",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_leads_location_id"), "leads", ["location_id"], unique=False)
    op.create_index(op.f("ix_leads_org_id"), "leads", ["org_id"], unique=False)
    op.create_index(
        "uq_leads_source_external_id",
        "leads",
        ["source", "external_id"],
        unique=True,
        postgresql_where="external_id IS NOT NULL",
    )
    op.create_table(
        "location_lot_on_hand",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("on_hand", sa.Integer(), nullable=False),
        sa.CheckConstraint("on_hand >= 0", name="ck_on_hand_non_negative"),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["lots.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("location_id", "lot_id"),
    )
    op.create_index(
        op.f("ix_location_lot_on_hand_org_id"), "location_lot_on_hand", ["org_id"], unique=False
    )
    op.create_table(
        "revenue_reports",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("gross_cents", sa.BigInteger(), nullable=False),
        sa.Column("refunds_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "net_base_cents",
            sa.BigInteger(),
            sa.Computed("gross_cents - refunds_cents", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "status", sa.Enum("draft", "submitted", "locked", name="report_status"), nullable=False
        ),
        sa.Column("attested_by", sa.UUID(), nullable=True),
        sa.Column("attested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("gross_cents >= 0", name="ck_revenue_reports_gross_non_negative"),
        sa.CheckConstraint("refunds_cents >= 0", name="ck_revenue_reports_refunds_non_negative"),
        sa.ForeignKeyConstraint(
            ["attested_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["supersedes"],
            ["revenue_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_revenue_reports_location_id"), "revenue_reports", ["location_id"], unique=False
    )
    op.create_index(op.f("ix_revenue_reports_org_id"), "revenue_reports", ["org_id"], unique=False)
    op.create_index(op.f("ix_revenue_reports_period"), "revenue_reports", ["period"], unique=False)
    op.create_table(
        "royalty_line_items",
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("base_cents", sa.BigInteger(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("minimum_applied", sa.Boolean(), nullable=False),
        sa.Column("adjustments_cents", sa.BigInteger(), nullable=False),
        sa.Column("amount_due_cents", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["royalty_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_royalty_line_items_location_id"),
        "royalty_line_items",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_royalty_line_items_org_id"), "royalty_line_items", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_royalty_line_items_run_id"), "royalty_line_items", ["run_id"], unique=False
    )
    op.create_table(
        "shipments",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reversal_of", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("qty <> 0", name="ck_shipments_qty_nonzero"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["lots.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["reversal_of"],
            ["shipments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shipments_location_id"), "shipments", ["location_id"], unique=False)
    op.create_index(op.f("ix_shipments_lot_id"), "shipments", ["lot_id"], unique=False)
    op.create_index(op.f("ix_shipments_org_id"), "shipments", ["org_id"], unique=False)
    op.create_table(
        "variance_flags",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("period", sa.Date(), nullable=False),
        sa.Column("reported_net_base_cents", sa.BigInteger(), nullable=False),
        sa.Column("expected_floor_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "reviewed", "resolved", name="variance_status"),
            nullable=False,
        ),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_variance_flags_location_id"), "variance_flags", ["location_id"], unique=False
    )
    op.create_index(op.f("ix_variance_flags_org_id"), "variance_flags", ["org_id"], unique=False)
    op.create_index(op.f("ix_variance_flags_period"), "variance_flags", ["period"], unique=False)
    op.create_table(
        "consults",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("outcome IN ('no_show', 'no_sale', 'sale')", name="ck_consults_outcome"),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consults_lead_id"), "consults", ["lead_id"], unique=False)
    op.create_index(op.f("ix_consults_location_id"), "consults", ["location_id"], unique=False)
    op.create_index(op.f("ix_consults_org_id"), "consults", ["org_id"], unique=False)
    op.create_table(
        "sales",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("consult_id", sa.UUID(), nullable=False),
        sa.Column("plan_value_cents", sa.BigInteger(), nullable=False),
        sa.Column("planned_treatments", sa.Integer(), nullable=False),
        sa.Column("financing_flag", sa.Boolean(), nullable=False),
        sa.Column("sold_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("plan_value_cents > 0", name="ck_sales_plan_value_positive"),
        sa.CheckConstraint("planned_treatments > 0", name="ck_sales_planned_treatments_positive"),
        sa.ForeignKeyConstraint(
            ["consult_id"],
            ["consults.id"],
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sales_consult_id"), "sales", ["consult_id"], unique=False)
    op.create_index(op.f("ix_sales_location_id"), "sales", ["location_id"], unique=False)
    op.create_index(op.f("ix_sales_org_id"), "sales", ["org_id"], unique=False)
    op.create_table(
        "treatments",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("sale_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["sale_id"],
            ["sales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_treatments_location_id"), "treatments", ["location_id"], unique=False)
    op.create_index(op.f("ix_treatments_org_id"), "treatments", ["org_id"], unique=False)
    op.create_index(op.f("ix_treatments_sale_id"), "treatments", ["sale_id"], unique=False)
    op.create_table(
        "administrations",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("lot_id", sa.UUID(), nullable=False),
        sa.Column("treatment_id", sa.UUID(), nullable=True),
        sa.Column("synthetic_patient_ref", sa.Text(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("administered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reversal_of", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("qty <> 0", name="ck_administrations_qty_nonzero"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["lot_id"],
            ["lots.id"],
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["reversal_of"],
            ["administrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["treatment_id"],
            ["treatments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_administrations_location_id"), "administrations", ["location_id"], unique=False
    )
    op.create_index(op.f("ix_administrations_lot_id"), "administrations", ["lot_id"], unique=False)
    op.create_index(op.f("ix_administrations_org_id"), "administrations", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_administrations_treatment_id"), "administrations", ["treatment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_administrations_treatment_id"), table_name="administrations")
    op.drop_index(op.f("ix_administrations_org_id"), table_name="administrations")
    op.drop_index(op.f("ix_administrations_lot_id"), table_name="administrations")
    op.drop_index(op.f("ix_administrations_location_id"), table_name="administrations")
    op.drop_table("administrations")
    op.drop_index(op.f("ix_treatments_sale_id"), table_name="treatments")
    op.drop_index(op.f("ix_treatments_org_id"), table_name="treatments")
    op.drop_index(op.f("ix_treatments_location_id"), table_name="treatments")
    op.drop_table("treatments")
    op.drop_index(op.f("ix_sales_org_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_location_id"), table_name="sales")
    op.drop_index(op.f("ix_sales_consult_id"), table_name="sales")
    op.drop_table("sales")
    op.drop_index(op.f("ix_consults_org_id"), table_name="consults")
    op.drop_index(op.f("ix_consults_location_id"), table_name="consults")
    op.drop_index(op.f("ix_consults_lead_id"), table_name="consults")
    op.drop_table("consults")
    op.drop_index(op.f("ix_variance_flags_period"), table_name="variance_flags")
    op.drop_index(op.f("ix_variance_flags_org_id"), table_name="variance_flags")
    op.drop_index(op.f("ix_variance_flags_location_id"), table_name="variance_flags")
    op.drop_table("variance_flags")
    op.drop_index(op.f("ix_shipments_org_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_lot_id"), table_name="shipments")
    op.drop_index(op.f("ix_shipments_location_id"), table_name="shipments")
    op.drop_table("shipments")
    op.drop_index(op.f("ix_royalty_line_items_run_id"), table_name="royalty_line_items")
    op.drop_index(op.f("ix_royalty_line_items_org_id"), table_name="royalty_line_items")
    op.drop_index(op.f("ix_royalty_line_items_location_id"), table_name="royalty_line_items")
    op.drop_table("royalty_line_items")
    op.drop_index(op.f("ix_revenue_reports_period"), table_name="revenue_reports")
    op.drop_index(op.f("ix_revenue_reports_org_id"), table_name="revenue_reports")
    op.drop_index(op.f("ix_revenue_reports_location_id"), table_name="revenue_reports")
    op.drop_table("revenue_reports")
    op.drop_index(op.f("ix_location_lot_on_hand_org_id"), table_name="location_lot_on_hand")
    op.drop_table("location_lot_on_hand")
    op.drop_index(
        "uq_leads_source_external_id",
        table_name="leads",
        postgresql_where="external_id IS NOT NULL",
    )
    op.drop_index(op.f("ix_leads_org_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_location_id"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_lots_product_id"), table_name="lots")
    op.drop_table("lots")
    op.drop_index(op.f("ix_locations_org_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_license_agreements_org_id"), table_name="license_agreements")
    op.drop_table("license_agreements")
    op.drop_index(op.f("ix_invoices_run_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_org_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_royalty_runs_period"), table_name="royalty_runs")
    op.drop_table("royalty_runs")
    op.drop_table("products")
    op.drop_table("orgs")
    # ### end Alembic commands ###
